### ISSUE TITLE
Error for pytorch-lightning

### ISSUE THREAD

**Issue by wcycqjy** [JusperLee/CTCNet#10]
Thanks for sharing your excellent work! But I confronted an error and thus asking for help. When I run the trainer.fit(system) in train_ctc.py, there is an error said: The `LightningModule.on_epoch_end` hook was removed in v1.8. Please use `LightningModule.on_<train/validation/test>_epoch_end` instead.

But I can't find any possible code in train_ctc.py to fix it. I think this happens to the wrong version of pytorch-lightning, but the version is exactly what you wrote in the readme. So can you help me fix this problem?

**Comment by JusperLee** [comment]
#8

**Comment by wcycqjy** [comment]
Thanks for your reply. I see that issue but get confused where to put the new code def on_validation_epoch_end(self). Could you explain it more explicitly?

**Comment by wcycqjy** [comment]
I find it, thanks.

**Comment by 1ralen** [comment]
> I find it, thanks.

I have the same confusion. Should I replace “def on_epoch_end(self)” with the new code ‘’def on_validation_epoch_end(self)‘’? Can I just follow the error message and change ‘’def on_epoch_end(self)‘’ to ‘’def on_train_epoch_end(self)‘’ directly?
